### ISSUE TITLE
Samurai's wallet was downloaded from the wrong address

### ISSUE THREAD

**Issue by Cy-zhen** [Platdot-network/Platdot#1]
The downloaded version is the official version:`samurai-chrome-8.0.11.zip` not `samurai-devnet-chrome-8.0.11.zip`
<img src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/PlatONtest01.png">

**Comment by hacpy** [comment]
感谢反馈！这个是官方的教程下载的就是主网钱包，钱包插件的测试版可以在[pladot](https://platdot.chainx.org/#/)界面下载，群公告也给出了相应链接
