### ISSUE TITLE
关于测试网与主网之间的转换BUG

### ISSUE THREAD

**Issue by 740400019** [Platdot-network/Platdot#10]
第一次先装了主网插件并创建钱包，第二次删除了主网插件，安装测试网插件，安装测试网插件界面显示：欢迎使用 Samurai 测试版，安装完成后重新创建测试网钱包，还是创建并注册了主网，无法切换到测试网，已经重复测试3遍。
![NF0YZEKACMMDQB2981A~ON](https://user-images.githubusercontent.com/82109578/114513682-0984d280-9c6d-11eb-8e37-d970e25c7b93.png)

**Comment by 740400019** [comment]
附上测试网插件安装截图
![@MKI3YT1P HT3@ SJIF22EX](https://user-images.githubusercontent.com/82109578/114514057-74360e00-9c6d-11eb-9808-a52de403eded.png)

**Comment by 740400019** [comment]
![8P6M{KZ~09_)AKD$R29 YIM](https://user-images.githubusercontent.com/82109578/114514287-b19a9b80-9c6d-11eb-9f07-e42005326036.png)

**Comment by 740400019** [comment]
![KR{@ZV7V$QX$I%GIV)T $2X](https://user-images.githubusercontent.com/82109578/114514523-f6becd80-9c6d-11eb-9526-6e77b764d52c.png)

**Comment by hacpy** [comment]
谢谢反馈！你需要下载测试网的钱包插件使用，测试网钱包插件应该是这样的名字[samurai-devnet-chrome-8.0.11.zip](https://raw.githubusercontent.com/AlayaNetwork/Samurai/develop/devnet/samurai-devnet-chrome-8.0.11.zip)
.如果主网钱包有影响可以将它关闭.

**Comment by 740400019** [comment]
测试网的钱包我有下载，安装显示是测试网，正式进入后是主网，应该是bug












币小熊邮箱
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月13日(周二) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Platdot-network/Platdot] 关于测试网与主网之间的转换BUG (#10)




 
谢谢反馈！你需要下载测试网的钱包插件使用，测试网钱包插件应该是这样的名字samurai-devnet-chrome-8.0.11.zip
 .如果主网钱包有影响可以将它关闭.

**Comment by hacpy** [comment]
那这个问题应该是钱包的bug，你可以试试去他们[钱包的仓库](https://github.com/AlayaNetwork/Samurai)提issue.

**Comment by 740400019** [comment]
钱包不是你这边的吗？那这算入bug奖励吗？












币小熊邮箱
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月13日(周二) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Platdot-network/Platdot] 关于测试网与主网之间的转换BUG (#10)




 
那这个问题应该是钱包的bug，你可以试试去他们钱包的仓库提issue.

**Comment by hacpy** [comment]
钱包是PlatON提供的，我们也只是使用。
