### ISSUE TITLE
测试发现BUG

### ISSUE THREAD

**Issue by AndyQ-hoo** [Platdot-network/Platdot#18]
1.发行成功了，没有记录，刷新之后还是没有
<img width="1259" alt="suke1" src="https://user-images.githubusercontent.com/78330549/114968067-2a853780-9ea8-11eb-868c-b2c74d76811d.png">
<img width="1202" alt="suke1 1" src="https://user-images.githubusercontent.com/78330549/114968074-2f49eb80-9ea8-11eb-867b-b54cc7a85a0d.png">

2.发行成功，Alaya账户仍为0，导致无法赎回
<img width="1141" alt="bug2" src="https://user-images.githubusercontent.com/78330549/114968079-353fcc80-9ea8-11eb-8112-b4b3c7a3c1d7.png">

ChainX地址：5QeRzeE41bkVpcHkcSpbhaAEdSALfs2QeZpFYjJeQherSPMv
ATP：atp142tstdzdg0dn3jvsl2a5f74pk9lqsag8wjapmg

**Comment by hacpy** [comment]
非常感谢您的反馈！这是我们的问题，但这并不是一个bug。上午我们在进行platdot的升级，加入了ChainX和Alaya之间的跨链支持，因而有一段时间服务器停止，现在已经在继续运行了。

**Comment by AndyQ-hoo** [comment]
> 非常感谢您的反馈！这是我们的问题，但这并不是一个bug。上午我们在进行platdot的升级，加入了ChainX和Alaya之间的跨链支持，因而有一段时间服务器停止，现在已经在继续运行了。

服务器停止应该发行不成功才对，现在恢复了。依然看不到发行的AKSM，还是0，好像掉入黑洞了。如果真的是主网，那不就是丢币了吗？这还不是bug？

**Comment by RJman-self** [comment]
您好，感谢您的反馈，币是不会丢失的，我们已经从历史中查询了您的交易并进行恢复。当时服务器停机是因为升级功能，预计升级的时间会比较短，就没有让网站停止运行，由此导致您发出了无响应的交易，对此我们非常抱歉给您的测试过程造成了困扰。现在测试网，没有区块浏览器，查看交易记录不是很方便，上了主网后是不会有类似问题的，您可以在主网浏览器上很轻松地对每一笔交易进行溯源。
![image](https://user-images.githubusercontent.com/44558375/115185968-72f45d80-a113-11eb-8533-3fed31ce8213.png)
