### ISSUE TITLE
no publish and redeem records

### ISSUE THREAD

**Issue by zonzpoo** [Platdot-network/Platdot#2]
Hi
#### Backtrace

发行
![image](https://user-images.githubusercontent.com/12594210/114409291-e14d9300-9bdc-11eb-9681-82a43fd816a2.png)

赎回
![image](https://user-images.githubusercontent.com/12594210/114409327-ea3e6480-9bdc-11eb-834d-c77c0669ecc2.png)

**Comment by hacpy** [comment]
谢谢反馈！这个是Alaya的scan浏览器没有开放接口，功能是已经实现了的，对现阶段测试无影响
