### ISSUE TITLE
测试过程中遇到的bug

### ISSUE THREAD

**Issue by hjj4238250** [Platdot-network/Platdot#22]
如下图所示 尝试多次发行 发行之后仅消失ksm币 并未获得aksm 更换网络节点与刷新均无法获得aksm 导致无法进行赎回步骤
![微信图片编辑_20210421222659](https://user-images.githubusercontent.com/82391321/115571033-31b9a480-a2f1-11eb-82da-a79be0484169.jpg)
![微信图片编辑_20210421222733](https://user-images.githubusercontent.com/82391321/115571044-32ead180-a2f1-11eb-9cda-2ec479ae9ed2.jpg)
![微信图片编辑_20210421222934](https://user-images.githubusercontent.com/82391321/115571047-341bfe80-a2f1-11eb-92de-5b56265e0261.jpg)

**Comment by hjj4238250** [comment]
PCX地址：5RR3TypVedeBXjpjdgNVEaq21EAZ6JVtzz519iJHEpBuaG64
atp地址：atp1m2h48xn7ayd55v42xzuf9fzaz2gzljcxtwmdfn

**Comment by RJman-self** [comment]
感谢您的反馈，昨晚在进行测试，服务器处于维护状态，您的AKSM现在已经恢复发放
![image](https://user-images.githubusercontent.com/44558375/115652526-0326e280-a360-11eb-90d0-16354f5e4f0b.png)
