### ISSUE TITLE
Failed Publish KSM

### ISSUE THREAD

**Issue by asrafs** [Platdot-network/Platdot#23]
At task 1
I am failed Publish KSM and not show at alaya.network scan.
first 100KSM from KSM test coins. 
this is a second publish KSM test 
https://devnetscan.alaya.network/address-detail?address=atp1kpp5gkwqps88auff5hlg50jufxzcwqrv58l22e
my address KSM test coins : 5FCQ9sLESvkcbXMAuKv47SCLe3uRzLGefh4WoFfjiqCbujJF
my address ATP test coins : atp1kpp5gkwqps88auff5hlg50jufxzcwqrv58l22e

![Faile AKSM](https://user-images.githubusercontent.com/83138579/115970902-bc0f3c00-a56f-11eb-9504-07dfa3bc1cbd.jpg)
balance less than 100, thats show loss 81 KSM at first test.
maybe that can be checked for future.
myPCX mainnet address: 5QeQiaJ1qFVNUXSKB2NutWeFSH72Q9P7WDSVDJ9tYmSDJ6mT
myATP address: atp1nq2hvnqsakcz5rrjajcah6fp7ucq3eyhn663xt

**Comment by RJman-self** [comment]
Thank you for your feedback. We checked that when you sent the transaction, the Alaya network was congested for a period of time, which led to a successful release but did not receive the account. Now we have successfully resumed your distribution transaction. I am sorry to have caused you any trouble.
![image](https://user-images.githubusercontent.com/44558375/115977543-dc5cec00-a5ab-11eb-82f7-4c63f3e714bd.png)
