### ISSUE TITLE
PlatDOT usage feedback

### ISSUE THREAD

**Issue by Cy-zhen** [Platdot-network/Platdot#3]
* Records of issues, redemptions, transfers are not shown
<img src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/iss.jpg">

* The page and wallet data cannot be synchronized
<img src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/PlatONtest02.png">

**Comment by hacpy** [comment]
Thanks for the feedback! This is that Alaya's scan browser does not have an open interface, the function has been implemented, and it has no impact on the current test.The wallet and the page are not synchronized, you can refresh and try！
