### ISSUE TITLE
Interaction problem

### ISSUE THREAD

**Issue by Cy-zhen** [Platdot-network/Platdot#4]
`KSM-->AKSM` The interaction was successful but not displayed.
And the amount of `AKSM` in the wallet doesn't change.
Click the gif to jump to the video 👇 
[![Watch the video](https://raw.githubusercontent.com/Cy-zhen/MEME/main/GIF/github01.gif)](https://youtu.be/zYZhKqXkQbg)

**Comment by Cy-zhen** [comment]
If the interaction is successful, `KSM` will be deducted, but the number of `AKSM` will not be increased.
Causes the next operation to be unable to complete.

**Comment by hacpy** [comment]
We are very sorry that the server was shut down early this morning, and we did not find out in time. Now that we have fixed the problem, you can continue to use it. Thank you so much for your feedback!
