### ISSUE TITLE
AKSM decreased BUT KSM NOT increased ！

### ISSUE THREAD

**Issue by HeroFang** [Platdot-network/Platdot#6]
I had 47.9894 KSMs and 50.8890  AKSMs before I  redeemed. And after I redeemed 20 AKSMs to KSMs. I  got 30.8579 AKSMs (  with 20 redeemed and 0.0311 fee) and still 47.9894 KSMs (which exactly should be 67.9894).Just see:
![task2](https://user-images.githubusercontent.com/60031807/114491246-e516ff00-9c48-11eb-88c3-6a25384d9089.png)
![task3](https://user-images.githubusercontent.com/60031807/114491253-ea744980-9c48-11eb-961d-9070072080f1.png)

and also the Publish Record and Redeem Record do NOT show any records yet .

PCX mainnet address:  5VJ1T6URYRh6zfEG3PDb9AeSLUMJuPHGfEj2Vot3tyLqPcaq
ATP recipient address:  atp1ulu6e258693y825u73qn2yw9le5aukldwsqnl2

**Comment by hacpy** [comment]
We are very sorry that the server was shut down early this morning, and we did not find out in time. Now that we have fixed the problem, you can continue to test it. Thank you so much for your feedback!
