### ISSUE TITLE
KSM decrease,but AKSM not increase

### ISSUE THREAD

**Issue by hanlei111** [Platdot-network/Platdot#7]
I have issue AKSM , and it succeced, and my KSM decrease, but AKSM not increase
![ksm](https://user-images.githubusercontent.com/82431940/114499427-a6894080-9c58-11eb-8794-d5ff2f27b639.png)

**Comment by hacpy** [comment]
We are very sorry that the server was shut down early this morning, and we did not find out in time. Now that we have fixed the problem, you can continue to use it. Thank you so much for your feedback!
