### ISSUE TITLE
发行KSM兑换比例错误,50KSM兑换了139AKSM

### ISSUE THREAD

**Issue by zhouxiaofeng-zxf** [Platdot-network/Platdot#9]
> 
测试地址 5GYTKhyk5f5z4S5YErZToGTqJhNJjLLtzUKVxebtb1YCQRpN   -> atp14464fcv5nshct8nup9zflk65zydn53ugnef3hp

PCX:5TairT8nPdwPvev6tExW9NviKNXVmCFW8uWzCnPJ6SXAeqdA
ATP:atp1zyyydwj6yzntfc50q8g728x2rrt7y6fmu0w5ql
![image](https://user-images.githubusercontent.com/54530820/114503227-8a3cd200-9c5f-11eb-8010-d12e01379690.png)

**Comment by RJman-self** [comment]
![image](https://user-images.githubusercontent.com/44558375/114507949-6af57300-9c66-11eb-88b0-8fd2c06fabe2.png)
你上午是不是向这个发行了KSM，由于服务端中断，在处理后到账了
